version: 3

output: prefixed

vars:
  ROOT:
    sh: pwd

tasks:
  test:
    cmds:
      - echo "hello"
  default:
    desc: Generate a base application layout with app name specified by APP_NAME
      parameter
    cmds:
      - task: clean
      - echo "Creating project package for {{.APP_NAME}}"
      - rm -rf bin/build/{{.APP_NAME}} || true
      - rm -rf bin/build/builds/{{.APP_NAME}} || true
      - mkdir -p bin/build/{{.APP_NAME}}
      - mkdir -p bin/build/builds/{{.APP_NAME}}
      - cp -r cmd/goproject/ bin/build/{{.APP_NAME}}
      - find bin/build/{{.APP_NAME}} -type d -empty -exec touch {}/.keep \;
      - task: package
    preconditions:
      - sh: "[ '{{.APP_NAME}}' != '' ]"
        msg: APP_NAME must be given. e.g. task APP_NAME="test"

  package:
    dir: bin/build/
    cmds:
      - zip -r {{.APP_NAME}}.zip {{.APP_NAME}}
      - mv {{.APP_NAME}}.zip {{.ROOT}}/bin/build/builds/{{.APP_NAME}}/
      - tar -cvzf {{.APP_NAME}}.tar.gz {{.APP_NAME}}
      - mv {{.APP_NAME}}.tar.gz {{.ROOT}}/bin/build/builds/{{.APP_NAME}}/

  clean:
    cmds:
      - rm -rf bin/build/{{.APP_NAME}}
      - rm -rf bin/build/builds/{{.APP_NAME}}